### PR TITLE
Fix user archival

### LINKED ISSUE #428: User_cleanup_Job doesn't run properly
image

this looks like to be the case for the last 2 years according to sentry, it gives multiple user who should have been archived but haven't due to this bug

### PR DESCRIPTION
**Pull request by wilco375**
### Summary
Fixes #428

User archival failed because a form can only have one response per user, but if multiple responses are archived they all get user id 0, which caused this validation to fail. The validation now explicitly excludes the archived user (id 0). 
I also changed the user update statement to throw an error once an update fails. This makes it more clear where the error occurs. Regardless of this, user archival will fail anyways if the update fails because of foreign key constraints once the user is attempted to be deleted (as has been happening until now).

### CODE REVIEW

File: app/models/form/response.rb [hunk 1]
```diff
@@ -8,7 +8,7 @@ class Response < ApplicationRecord
     has_many :closed_question_answers, dependent: :destroy
     has_many :closed_questions, through: :closed_question_answers, source: :question
 
-    validates :user, uniqueness: { scope: :form }
+    validates :user, uniqueness: { scope: :form, unless: -> { !user.nil? && !user.id.nil? && user.id.zero? } }
```
Comment (wilco375) [inline app/models/form/response.rb:11]: I know this looks ugly but the linter does not want me to use `== 0` 🙄

**Review by lodewiges — APPROVED** [review]
